language: python

python:
  - 3.6

before_install:
  -

install:
  - make dev-setup

script:
  - make test

after_success:
  - export CODECOV_TOKEN=5d4e4171-62e5-494b-9070-31ef527a4911 # py-ml/classifier
  - bash <(curl -s https://codecov.io/bash) -t 5d4e4171-62e5-494b-9070-31ef527a4911